import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Einer Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.center}`}>
        <div className={styles.description}>
          <div>
              <Image
                src="/einer.svg"
                alt="Einer Logo"
                className={`${styles.vercelLogo}`}
                width={500}
                height={40}
                priority
              />
          </div>
        </div>
        <h1 className={`${inter.className} ${styles.SprintReport}`}>Sprint 1 Report</h1>
        <div className={styles.grid}>
        <div className={`${styles.thirteen} ${styles.A}`}>
            <h1 className={inter.className}>+500 <Image src="/gh.svg" alt="Gh logo" width={30} height={30} /></h1>
            <h3 className={inter.className}>Contribuições em 10 repositórios</h3>
          </div>
          <div className={`${styles.thirteen} ${styles.B}`}>
            <Image src="vitest.svg" alt="vitest logo" style={{ filter: 'drop-shadow(0 0 0.5rem yellow)' }} width={50} height={50} />
            <h1 className={inter.className}>Sistema de testes e controle de qualidade com Integração Contínua</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.C}`}>
            <Image src="lock.svg" alt="lock icon" width={45} height={45} />
            <h1 className={inter.className}>Autenticação unificada entre plataformas</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.D}`}>
            <Image src="folders.svg" alt="lock icon" width={45} height={45} />
            <h1 className={inter.className}>Armazenamento, compressão e otimização de arquivos</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.E}`}>
            <h1 className={inter.className}>Grafico 1</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.F}`}>
            <h1 className={inter.className}>Einer</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.G}`}>
            <h1 className={inter.className}>Grafico 2</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.H}`}>
            <Image src="terminal.svg" alt="terminal icon" width={45} height={45} />
            <h1 className={inter.className}>Serviço de Log tracking centralizado</h1>
          </div>
           <div className={`${styles.thirteen} ${styles.I}`}>
            <div>
              <Image src="rust.svg" alt="rust icon" width={65} height={65} />
              <Image src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-plain.svg" style={{ filter: 'drop-shadow(0 0 0.3rem blue)' }} alt="Ts logo" width={45} height={45} />
            </div>
            <h1 className={inter.className}>Einer Toolchain + SDKs para desenvolvedores</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.J}`}>
            <div>
              <Image src="vsdia.svg" alt="vsdia icon" width={45} height={45} style={{ filter: 'drop-shadow(0 0 0.3rem green)' }} />
              <Image src="planner.svg" alt="planner icon" width={45} height={45} style={{ filter: 'drop-shadow(0 0 0.3rem dodgerblue)' }} />
              <Image src="borum.svg" alt="borum icon" width={45} height={45} style={{ filter: 'drop-shadow(0 0 0.3rem green)' }} />
            </div>
            <h1 className={inter.className}>Versão beta em breve</h1>
          </div>
        </div>
      </main>
    </>
  )
}
