import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Einer Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.center}`}>
        <div className={styles.description}>
          <div>
              <Image
                src="/einer.svg"
                alt="Einer Logo"
                className={`${styles.vercelLogo}`}
                width={500}
                height={40}
                priority
              />
          </div>
        </div>
        <h1 className={`${inter.className} ${styles.SprintReport}`}>Sprint 1 Report</h1>
        <div className={styles.grid}>
        <div className={`${styles.thirteen} ${styles.A}`}>
            <h1 className={inter.className}>Dado 1</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.B}`}>
            <h1 className={inter.className}>Dado 2</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.C}`}>
            <h1 className={inter.className}>Dado 3</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.D}`}>
            <h1 className={inter.className}>Dado 4</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.E}`}>
            <h1 className={inter.className}>Grafico 1</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.F}`}>
            <h1 className={inter.className}>Einer</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.G}`}>
            <h1 className={inter.className}>Grafico 2</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.H}`}>
            <h1 className={inter.className}>Dado 5</h1>
          </div>
           <div className={`${styles.thirteen} ${styles.I}`}>
            <h1 className={inter.className}>Dado 6</h1>
          </div>
          <div className={`${styles.thirteen} ${styles.J}`}>
            <h1 className={inter.className}>Dado 7</h1>
          </div>
        </div>
      </main>
    </>
  )
}
